// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://wuvukfhwyttboztzoojt.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1dnVrZmh3eXR0Ym96dHpvb2p0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzA0ODU5MTIsImV4cCI6MjA0NjA2MTkxMn0.OTJ6XxUOpwJpgOzclCIsu8iz2b8fsoyCCelfoHZL3Z8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);